name: CI

on:
  # push代码时触发workflow
  push:
    branches:
      - master
      - main
    tags:
      - "*"
    # 忽略README.md
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'Doxyfile.in'
      - '.clang-format'
      - '.git*'
  # pull_request时触发workflow
  pull_request:
    paths-ignore:
    - '*.md'
    - 'LICENSE'
    - 'Doxyfile.in'
    - '.clang-format'
    - '.git*'

jobs:
  cmake-build:
    strategy:
      fail-fast: false
      # 矩阵配置
      matrix:
        configuration:
          - Release
        config:
          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            qt_version: "5.15.2"
            modules: ""

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            qt_version: "5.15.2"
            modules: ""

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            qt_version: "5.15.2"
            modules: ""

          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            qt_version: "6.3.0"
            modules: "qt5compat"

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            qt_version: "6.3.0"
            modules: "qt5compat"

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            qt_version: "6.3.0"
            modules: "qt5compat"

    # 运行平台
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.config.qt_version }}
        modules: ${{ matrix.config.modules }}

    - name: Setup (Linux)
      if: startsWith (matrix.config.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.config.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} 

    - name: Build with ${{ matrix.config.compiler }}
      run: cmake --build build --config ${{ matrix.configuration }}
