name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - Release

        config:
          - toolchain: linux-gcc
            os: ubuntu-20.04
            compiler: gcc
            qt_version: "5.15.2"
            modules: ""

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            qt_version: "5.15.2"
            modules: ""

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            qt_version: "5.15.2"
            modules: ""

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.config.qt_version }}
        modules: ${{ matrix.config.modules }}

    - name: Setup (Linux)
      if: startsWith (matrix.config.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.config.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.config.compiler }}
      run: cmake --build build --config ${{ matrix.configuration }}

    # - name: Test
    #   working-directory: build
    #   env:
    #     CTEST_OUTPUT_ON_FAILURE: 1
    #   run: ctest -C ${{ matrix.configuration }}
