name: Ubuntu
# Qt官方没有linux平台的x86包
on:
  # push代码时触发workflow
  push:
    branches:
      - master
      - main
    tags:
      - "*"
    # 忽略README.md
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'Doxyfile.in'
      - '.clang-format'
      - '.git*'
  # pull_request时触发workflow
  pull_request:
    paths-ignore:
    - '*.md'
    - 'LICENSE'
    - 'Doxyfile.in'
    - '.clang-format'
    - '.git*'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-20.04]
        qt_ver: [5.15.2,6.3.0]
        qt_arch: [gcc_64]
        exclude: 
          # Qt6.2.2 need GLIBC_2.28, ubuntu 18.04 have not.
          - os: ubuntu-18.04
            qt_ver: 6.2.2
            qt_arch: gcc_64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev libxkbcommon-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure (${{ matrix.configuration }})
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: Build 
        run: cmake --build build
